;;;;; bender – Copyright (c) 2014 Sven Michael Klose <pixel@copei.de>

(load "./environment/platforms/shared/read-binary.lisp")
(load "./environment/platforms/shared/xml2lml.lisp")

(load "6502.lisp")
(load "instruction.lisp")
(load "print.lisp")
(load "disassembler.lisp")
(load "instruction-map.lisp")
(load "labels.lisp")
(load "tokenizer.lisp")
(load "parser.lisp")
(load "labels-to-exprs.lisp")
(load "helpers.lisp")
(load "assembler.lisp")
(load "vice.lisp")
(load "bin2cbmtap.lisp")
(load "decode-cbmtap.lisp")
(load "tap.lisp")
(load "tap2wav.lisp")
(load "tests.lisp")

(dump-system "bender")
(quit)
