; bender – Copyright (c) 2015,2024 Sven Michael Klose <pixel@copei.de>

(fn gen-c-cycle-map (path)
  (format t "; Generating C instruction cycle map…~%")
  (with-output-file o path
    (format o "/* Generated by https://github.com/SvenMichaelKlose/bender/src/gen-c-cycle-map.lisp */~%")
    (format o "int cycle_map[256] = {~%")
    (princ (apply #'+ (pad (@ [string (? _
                                         (instruction-cycles (opcode-instruction (generate-opcode _. ._)))
                                         -1)]
                              (array-list *opcode-map*))
                           ","))
           o)
    (format o "~%};~%")))
