; bender – Copyright (c) 2014–2015 Sven Michael Klose <pixel@copei.de>

(load "./tre/environment/platforms/shared/read-binary.lisp")
(load "./tre/environment/platforms/shared/xml-entities.lisp")
(load "./tre/environment/platforms/shared/xml2lml.lisp")

(load "src/6502.lisp")
(load "src/instruction.lisp")
(load "src/print.lisp")
(load "src/disassembler.lisp")
(load "src/instruction-map.lisp")
(load "src/cycles.lisp")
(load "src/labels.lisp")
(load "src/tokenizer.lisp")
(load "src/parser.lisp")
(load "src/labels-to-exprs.lisp")
(load "src/helpers.lisp")
(load "src/assembler.lisp")
(load "src/vice.lisp")
(load "src/bin2cbmtap.lisp")
(load "src/decode-cbmtap.lisp")
(load "src/tap.lisp")
(load "src/tap2wav.lisp")
(load "src/ascii2petscii.lisp")
(load "src/cbm-basic.lisp")
(load "src/model.lisp")
(load "src/tests.lisp")
(load "src/vic-palettes.lisp")
(load "src/gen-c-cycle-map.lisp")
(load "src/gen-c-emulator.lisp")
(load "src/gen-c-opcode-map.lisp")

(gen-c-cycle-map "c/cycle-map.c")
(gen-c-emulator "c/6502-instructions.c")
(gen-c-opcode-map "c/opcode-map.c")
(dump-system "bender")
(quit)
